apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
      # can be used by a single node
    - ReadWriteOnce
  resources:
    requests:
      # we are requesting 2GB of space, could be 1000Gi or whatever.
      storage: 2Gi